### ISSUE TITLE
衰減月報> EPA測站原始資料若無測值，平台會以0替代，會造成計算上有誤差。

### ISSUE THREAD

**Issue by karateboy** [karateboy/SensorManager#1]
![image](https://user-images.githubusercontent.com/1067042/119649171-e9902380-be54-11eb-8424-2f49f1c65660.png)

**Comment by karateboy** [comment]
偏差率以0替代是因為，如果環保署測值是0 ，會出現除以0的問題

**Comment by haopingchung** [comment]
excel中的bias公式裡有寫到EPA及sensor測值皆要大於0才會計算(避免錯誤值),主要是若EPA無效數據(空格)都以0替代會造成R2結果偏差大(如110/3/11 16:00~3/12 8:00)

**Comment by karateboy** [comment]
已經修正
