### ISSUE TITLE
6/3會議討論內容 - 資料查詢 

### ISSUE THREAD

**Issue by karateboy** [karateboy/SensorManager#10]
三、資料查詢
- [x] 1. 資料庫小時值算法修改(小時平均值)
- [x] 2. 系統管理新增"測點基本資料"查詢功能(即各區域感測器資料表)，若於平台修改內容，相關聯資料也會同步變動

**Comment by karateboy** [comment]
已經修正

**Comment by haopingchung** [comment]
2. (a)測點管理中，設備碼與代碼位置顛倒
    (b)filter：群組可放最右側(類型後方)
    (c)除目前資料外，是否可加入其餘欄位(目標、路名...等)

**Comment by karateboy** [comment]
已經完成

**Comment by karateboy** [comment]
已經修正  就先關掉了
