### ISSUE TITLE
6/3會議討論內容 - 美編

### ISSUE THREAD

**Issue by karateboy** [karateboy/SensorManager#11]
四、美編
- [x] 1. 濃度圖縮小(盈儒製作中)
- [x] 2. 地圖上EPA、感測器濃度圖框更換(大圓圈為EPA)
![image](https://user-images.githubusercontent.com/84848815/120628725-9a22a680-c497-11eb-9477-da45213ca349.png)
- [x] 4. 地圖filter美化(自由發揮)
- [x] 3. 儀錶板 即時資訊/SAQ-200及210，移除/

**Comment by haopingchung** [comment]
1. 
![圖例0604](https://user-images.githubusercontent.com/84848815/120784162-61013980-c55e-11eb-8feb-1ac49ccb9faa.png)

**Comment by karateboy** [comment]
Icon 有夠醜  再花點時間調整...
