### ISSUE TITLE
玫瑰圖移除校正小時值及無效數據

### ISSUE THREAD

**Issue by haopingchung** [karateboy/SensorManager#121]

**Comment by karateboy** [comment]
Fix in 1.3.26

**Comment by haopingchung** [comment]
想確認下玫瑰圖的百分比是不是正確的，因為用小時值算出來後去比較，有點落差
![image](https://user-images.githubusercontent.com/84848815/147523597-81d963a0-2303-45af-bc98-aa1e12a511aa.png)

**Comment by karateboy** [comment]
確實有bug, 首先區域是包含下限, 不包含上限. 所以百分比如圖
![image](https://user-images.githubusercontent.com/1067042/147539396-cbef4254-78e8-4845-9b5e-99025c75226f.png)

**Comment by karateboy** [comment]
時間輸入那邊有除了顯示的日期, 原本還有包含現在的小時, 分鐘. 經過調整後. 百分比已經一致了
(1.3.27)
