### ISSUE TITLE
1/7 屏東赤山老厝調整

### ISSUE THREAD

**Issue by chingyinging** [karateboy/SensorManager#126]
村長訴求：**字太小，站遠看不清楚**
建議可改善方式：
1. 字體都請再放大 
2. 縮小「即時監測資訊」板塊 ：切齊總發電量方塊
3. 供電資訊和用電情形字體都請放大，用黑的字不要灰色
4. 控制系統字體也都請放大
5. 太陽能1→請改成**太陽能(2kW)**
6. 太陽能2→請改成**太陽能(4kW)**

**Comment by karateboy** [comment]
已經修正了...
檢查一下看看有沒有漏掉的
