### ISSUE TITLE
主畫面地圖EPA測站

### ISSUE THREAD

**Issue by haopingchung** [karateboy/SensorManager#13]
6/7 查看平台發現EPA測站濃度無顯示(於測點管理改為啟用亦同)
![image](https://user-images.githubusercontent.com/84848815/120966154-677af580-c798-11eb-9bf4-8e3d4f82f134.png)

**Comment by karateboy** [comment]
那個改一半....還沒改完

**Comment by haopingchung** [comment]
了解
