### ISSUE TITLE
中研院(雲科+台中)DAS待調整事項

### ISSUE THREAD

**Issue by haopingchung** [karateboy/SensorManager#130]
- [x] 1. 登入帳號不強制使用email格式
- [x] 2.日報表下載excel新增醒目提示
- [x] 3.月報查詢及excel新增醒目提示

**Comment by karateboy** [comment]
台中中研院測站已經更新

**Comment by haopingchung** [comment]
剛才確認，發現一些奇怪的現象...
- [ ] 1. SO2、CO、picarro在1/26 00:00~06:00都沒有小時值，但分鐘值正常
- [ ] 2. 上述儀器在26日凌晨數小時數據都被標註為校正
- [ ] 3. 25日23:02~23:41，這些儀器都斷線

這些儀器的共通點是都在2300校正，是否是那時候程序有發生異常?


另外，月報目前還是沒有顯示醒目提示，再麻煩協助處理

**Comment by haopingchung** [comment]
- [ ] picarro校正時段(23:00)在日報內並沒有被標註

**Comment by karateboy** [comment]
月報顯示的是日均值  所以沒有狀態碼的顯目顯示唷
