### ISSUE TITLE
主畫面地圖：待調整部分

### ISSUE THREAD

**Issue by haopingchung** [karateboy/SensorManager#2]
- [x] 1. EPA濃度字體大小調整與感測器一致，顏色改為紅色(以醒目為原則)

- [x] 2. 地圖加長(卷軸拉至底部時，畫面上僅出現地圖)

- [x] 3. AQI圖示再縮小，圖中文字改為數字(請盈儒提供新圖)

**Comment by karateboy** [comment]
EPA字體改成紅色很醜...(紅底綠字)
為了突出, 改將Icon 放大

**Comment by haopingchung** [comment]
- [ ] 第三點的部分，需將長條圖移至最右側(如圖)

![image](https://user-images.githubusercontent.com/84848815/120256209-3a25d780-c2c0-11eb-986b-135ce13247b4.png)

- [ ] 另外地圖filter的區域劃分、類型、濃度 點擊x後會變成空白(縣市點x會變成不限)，是否可調整跟縣市一樣

**Comment by karateboy** [comment]
已修正
