### ISSUE TITLE
其他...

### ISSUE THREAD

**Issue by haopingchung** [karateboy/SensorManager#4]
- [x] 1. 歷史資料查詢新增選擇縣市功能，歷史資料趨勢圖亦同

- [x] 2. 新增"即時狀況資訊"(取代"即時數據")，顯示資訊包含設備序號、標示簡碼、代碼、位置、異常狀況(定值、<95%、通訊中斷)

**Comment by karateboy** [comment]
已經提供

**Comment by haopingchung** [comment]
- [ ] 即時狀況資訊之位置應顯示excel感測器資料表中"位置"欄位(因經緯度較不直覺)
