### ISSUE TITLE
9/7：中央研究院DAS LOGO

### ISSUE THREAD

**Issue by haopingchung** [karateboy/SensorManager#78]
- [x] 左上方改為中央研究院logo、右側頭像改為環境變遷中心LOGO(PPT是以7000為例)
[logo.pptx](https://github.com/karateboy/SensorManager/files/7118659/logo.pptx)

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/132542000-ab1f3bb0-5816-4bdd-9ea6-e2f128311b32.png)
