### ISSUE TITLE
6/3會議討論內容 - 月報

### ISSUE THREAD

**Issue by haopingchung** [karateboy/SensorManager#8]
一、月報
- [x] 1. 工作表2 C752需移除*100
- [x] 2. 最近會上傳新excel範本至onedrive
- [x] 3. 離群分析範例excel

**Comment by karateboy** [comment]
將原本issue 拆分開來, 方便追蹤

**Comment by haopingchung** [comment]
2. 以上傳excel(0604)

**Comment by haopingchung** [comment]
3. 離群分析初稿
[基隆離群分析初稿(0604).xlsx](https://github.com/karateboy/SensorManager/files/6597643/0604.xlsx)
說明(以K9SE01為例)：選擇地區與月份後，網頁上呈現盒鬚圖，但可以下載原始excel查看

**Comment by karateboy** [comment]
> 1. 已上傳excel(0604)
>    [基隆衰減分析excel(0604).xlsx](https://github.com/karateboy/SensorManager/files/6597499/excel.0604.xlsx)
已經更新, 原本整群平均與基隆測站的趨勢圖你刪掉了?

**Comment by karateboy** [comment]
離群分析已經更新, 但只有第一個群組有圖?

**Comment by haopingchung** [comment]
2. 200及210趨勢圖漏掉了，已補上
[基隆衰減分析excel(0607).xlsx](https://github.com/karateboy/SensorManager/files/6605520/excel.0607.xlsx)

**Comment by haopingchung** [comment]
3. 已更新檔案
[基隆離群分析(0607).xlsx](https://github.com/karateboy/SensorManager/files/6605911/0607.xlsx)

**Comment by haopingchung** [comment]
3. 已更新(補上其他群組的圖)
[基隆離群分析(0607).xlsx](https://github.com/karateboy/SensorManager/files/6606058/0607.xlsx)

另外請問，盒鬚圖是否有辦法直接呈現於網頁上?

**Comment by karateboy** [comment]
盒鬚圖可以呈現在網頁上....要分群組?

**Comment by haopingchung** [comment]
選擇縣市後可以選群組(可多選or全選)
