### ISSUE TITLE
3. 將mac系統上的程式包裝為一app

### ISSUE THREAD

**Issue by karateboy** [karateboy/SensorManager#81]

**Comment by karateboy** [comment]
https://sbt-native-packager.readthedocs.io/en/stable/gettingstarted.html#setup
發現其實有工具可以產生
但是產生工具要在Mac上執行

**Comment by karateboy** [comment]
目前已經產出Windows安裝程式MSI檔案

**Comment by karateboy** [comment]
https://stronghold365-my.sharepoint.com/:u:/g/personal/karateboy_stronghold_tw/EUfFRV_osLVFsuTBUlmlsrABC-LbP0mxCg9xJjy5pwe2_g?e=QpEtz0

**Comment by haopingchung** [comment]
mac anydesk：649017114/wecc27548312

ys當初說的意思應該是每次開啟程式時只要點一個icon，取代目前用終端機key路徑開啟
